- name: Setup DBserver
  hosts: db01
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
         name: mariadb-server
         state: present

    - name: Install Python MySQL
      yum:
         name: python3-PyMySQL
         state: present

    - name: Install expect
      yum:
         name: expect
         state: present

    - name: Start & Enable maridb service
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Secure MySQL installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root (enter for none):': '\r'
          'Set root password? [Y/n]': 'Y'
          'New password:': 'toto'
          'Re-enter new password:': 'toto'
          'Remove anonymous users? [Y/n]': 'Y'
          'Disallow root login remotely? [Y/n]': 'Y'
          'Remove test database and access to it? [Y/n]': 'Y'
          'Reload privilege tables now? [Y/n]': 'Y'
        creates: /root/.my.cnf

    - name: Create a new system user with name 'admin'
      user:
        name: admin
        password: "{{ '12345' | password_hash('sha512') }}"
        state: present

    - name: Give the 'admin' user sudo privileges
      lineinfile:
        path: /etc/sudoers
        line: 'admin ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Create a new database with name 'accounts'
      mysql_db:
        login_user: root
        login_password: 'toto'
        name: accounts
        state: present

    - name: Create database user with name 'admin'
      mysql_user:
        login_user: root
        login_password: 'toto'
        name: admin
        password: 12345
        priv: '*.*:ALL'
        state: present
